table Sales_data
	lineageTag: 971c000b-0c0e-4d66-a7ae-8d0412342c5d

	column Sale_ID
		dataType: int64
		formatString: 0
		lineageTag: 3e34644b-5a31-4eae-9b00-9bfcd8518eeb
		summarizeBy: count
		sourceColumn: Sale_ID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6556f011-3586-48cc-9fe3-4a012868eaa2
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: f16336ab-9b63-4e12-866f-fa22bce139c5
			defaultHierarchy: LocalDateTable_28507919-35aa-4b45-8bd6-db19406dc33b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Region
		dataType: string
		lineageTag: 9c3e810c-8223-4a7e-ba9f-a5871c54ab8b
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 9899d325-06aa-429a-829a-b217f991df6f
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: c95c3a2a-55cb-4236-acc9-77904e550933
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sales_Rep
		dataType: string
		lineageTag: 2bae7b50-149d-478e-ab11-655152d92497
		summarizeBy: none
		sourceColumn: Sales_Rep

		annotation SummarizationSetBy = Automatic

	column Units_Sold
		dataType: string
		lineageTag: 06b1aa43-e244-4652-aec5-6676153b1b85
		summarizeBy: none
		sourceColumn: Units_Sold

		annotation SummarizationSetBy = Automatic

	column Unit_Price
		dataType: string
		lineageTag: e57ba19a-5117-4aca-af8a-1453abc04a4b
		summarizeBy: none
		sourceColumn: Unit_Price

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: int64
		formatString: 0
		lineageTag: 8fb2e396-33f6-4e09-8994-c81974cfbb09
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Profit_Per_Unit
		dataType: double
		lineageTag: 9c006324-d8b7-41c0-ac9b-875cf88a2b51
		summarizeBy: sum
		sourceColumn: Profit_Per_Unit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_Sale
		dataType: double
		lineageTag: 5e7e1751-67a3-45e1-b7e1-f89c9721953c
		summarizeBy: sum
		sourceColumn: Total_Sale

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_Profit
		dataType: double
		lineageTag: 53b84474-7d08-45fd-8d98-6c671381b2c3
		summarizeBy: sum
		sourceColumn: Total_Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Irrelevant_Column
		dataType: string
		lineageTag: 682a1cc0-1a60-40a7-8868-87c3cc44da09
		summarizeBy: none
		sourceColumn: Irrelevant_Column

		annotation SummarizationSetBy = Automatic

	partition Sales_data = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Inobat\Desktop\Maab\Power BI\lesson-1_intro\homework_1\Sales_Dataset_Modified.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Sale_ID", Int64.Type}, {"Date", type date}, {"Region", type text}, {"Product", type text}, {"Category", type text}, {"Sales_Rep", type text}, {"Units_Sold", type any}, {"Unit_Price", type any}, {"Discount", Int64.Type}, {"Profit_Per_Unit", type number}, {"Total_Sale", type number}, {"Total_Profit", type number}, {"Irrelevant_Column", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",null,"South",Replacer.ReplaceValue,{"Region"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,"None",Replacer.ReplaceValue,{"Product"}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Replaced Value1", {{"Units_Sold", 2}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Replaced Errors", {"Unit_Price"}),
				    #"Removed Errors1" = Table.RemoveRowsWithErrors(#"Removed Errors", {"Total_Sale"}),
				    #"Removed Errors2" = Table.RemoveRowsWithErrors(#"Removed Errors1", {"Irrelevant_Column", "Total_Profit", "Total_Sale", "Profit_Per_Unit", "Discount", "Unit_Price", "Units_Sold", "Sales_Rep", "Category", "Product", "Region", "Date", "Sale_ID"})
				in
				    #"Removed Errors2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

