table 'Measures Table'
	lineageTag: 0a6aa74d-4cb8-455f-9e4e-2331d9086be0

	measure '% of region' = DIVIDE(CALCULATE(SUM(FactInternetSales[SalesAmount]),ALLEXCEPT(DimSalesTerritory,DimSalesTerritory[SalesTerritoryCountry],DimSalesTerritory[SalesTerritoryRegion])),CALCULATE(SUM(FactInternetSales[SalesAmount]),ALLEXCEPT(DimSalesTerritory,DimSalesTerritory[SalesTerritoryCountry])))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2348936b-706c-4baf-9c45-85afd59c2547

	measure 'Total sales' = SUM(FactInternetSales[SalesAmount])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d52f57dc-f46c-4bc3-970b-b411914f9560

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total sales without filters' = CALCULATE(SUM(FactInternetSales[SalesAmount]),ALL(DimSalesTerritory))
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: fede1215-39cb-44db-870a-b91f66b2b070

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total sales 2' = CALCULATE(SUM(FactInternetSales[SalesAmount]),all(DimProductCategory[EnglishProductCategoryName]),all(DimProductSubcategory[EnglishProductSubcategoryName]))
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: ce8410aa-e4f8-4adf-9541-aed04e286892

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure '% of sub category' = DIVIDE(CALCULATE(SUM(FactInternetSales[SalesAmount])), [Total sales 2])
		formatString: 0.000%;-0.000%;0.000%
		lineageTag: 187c41dc-c745-4558-babc-7917e748e235

	partition 'Measures Table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

