table Sales_Data
	lineageTag: c63db1d4-47f0-4d75-962d-43cd7bad8f1c

	column Region
		dataType: string
		lineageTag: 6600afc6-49c3-4836-aa35-e530f0cf5064
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 10d1c0b4-e5a3-48af-b989-5bb2a2a853c6
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 1a637438-78ec-4bf7-bd7d-48394e7d1360
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Total_Units_Sold
		dataType: double
		lineageTag: f5e0c396-c219-47e9-97c8-809620b80623
		summarizeBy: sum
		sourceColumn: Total_Units_Sold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Index
		dataType: int64
		formatString: 0
		lineageTag: eb51644b-ad68-4afd-858c-2c3e75f79139
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition Sales_Data = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Inobat\Desktop\Maab\Power BI\lesson-2_power_query\homework\Sales_Dataset.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Sale_ID", Int64.Type}, {"Date", type date}, {"Region", type text}, {"Product", type text}, {"Category", type text}, {"Sales_Rep", type text}, {"Units_Sold", Int64.Type}, {"Unit_Price", type number}, {"Discount", Int64.Type}, {"Profit_Per_Unit", type number}, {"Total_Sale", type number}, {"Total_Profit", type number}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Tax", each [Total_Sale] * 0.1),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Tax", type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type1", each [Profit_Per_Unit] < 50),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"Profit_Per_Unit", "Discount"}),
				    #"Added Custom1" = Table.AddColumn(#"Removed Columns", "Revenue", each [Units_Sold] * [Unit_Price]),
				    #"Split Column by Position" = Table.SplitColumn(#"Added Custom1", "Category", Splitter.SplitTextByRepeatedLengths(4), {"Category.1", "Category.2", "Category.3"}),
				    #"Inserted Month Name" = Table.AddColumn(#"Split Column by Position", "Month Name", each Date.MonthName([Date]), type text),
				    #"Inserted Year" = Table.AddColumn(#"Inserted Month Name", "Year", each Date.Year([Date]), Int64.Type),
				    #"Grouped Rows" = Table.Group(#"Inserted Year", {"Region", "Month Name", "Year"}, {{"Total_Units_Sold", each List.Sum([Units_Sold]), type nullable number}}),
				    #"Sorted Rows" = Table.Sort(#"Grouped Rows",{{"Region", Order.Ascending}, {"Month Name", Order.Ascending}, {"Year", Order.Ascending}}),
				    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 0, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

