table 'Sales_Data (2)'
	lineageTag: 02da5837-71f5-46b2-b6ab-b92291fd8062

	column Region
		dataType: string
		lineageTag: 88570f8b-455f-441f-ba1d-f7817a930742
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 21d27810-be98-4fad-a9db-a9571a43f374
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: d0480b4f-4970-403b-a86c-fc85650cbfff
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Total_Units_Sold
		dataType: double
		lineageTag: c52528ab-2144-4aa1-8da3-bcaf4aa2a2d6
		summarizeBy: sum
		sourceColumn: Total_Units_Sold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 8fd39320-be64-4caa-b342-89739d8340fb
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column IndexPlus1
		dataType: string
		lineageTag: 51a0ed13-254e-4fc6-90bc-af729f722e9a
		summarizeBy: none
		sourceColumn: IndexPlus1

		annotation SummarizationSetBy = Automatic

	partition 'Sales_Data (2)' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Inobat\Desktop\Maab\Power BI\lesson-2_power_query\homework\Sales_Dataset.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Sale_ID", Int64.Type}, {"Date", type date}, {"Region", type text}, {"Product", type text}, {"Category", type text}, {"Sales_Rep", type text}, {"Units_Sold", Int64.Type}, {"Unit_Price", type number}, {"Discount", Int64.Type}, {"Profit_Per_Unit", type number}, {"Total_Sale", type number}, {"Total_Profit", type number}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Tax", each [Total_Sale] * 0.1),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Tax", type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type1", each [Profit_Per_Unit] < 50),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"Profit_Per_Unit", "Discount"}),
				    #"Added Custom1" = Table.AddColumn(#"Removed Columns", "Revenue", each [Units_Sold] * [Unit_Price]),
				    #"Split Column by Position" = Table.SplitColumn(#"Added Custom1", "Category", Splitter.SplitTextByRepeatedLengths(4), {"Category.1", "Category.2", "Category.3"}),
				    #"Inserted Month Name" = Table.AddColumn(#"Split Column by Position", "Month Name", each Date.MonthName([Date]), type text),
				    #"Inserted Year" = Table.AddColumn(#"Inserted Month Name", "Year", each Date.Year([Date]), Int64.Type),
				    #"Grouped Rows" = Table.Group(#"Inserted Year", {"Region", "Month Name", "Year"}, {{"Total_Units_Sold", each List.Sum([Units_Sold]), type nullable number}}),
				    #"Sorted Rows" = Table.Sort(#"Grouped Rows",{{"Region", Order.Ascending}, {"Month Name", Order.Ascending}, {"Year", Order.Ascending}}),
				    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 0, 1, Int64.Type),
				    #"Added Custom2" = Table.AddColumn(#"Added Index", "IndexPlus1", each [Index] +1)
				in
				    #"Added Custom2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

