table Sales_Dataset
	lineageTag: 9f363f0d-8642-437c-a425-8961f7754b88

	column Region
		dataType: string
		lineageTag: 5dbac273-755e-4699-afa1-769fa66226dc
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Unit_sold_by_Region
		dataType: double
		lineageTag: 0625ad24-4685-428c-93bd-6fd37e3beb6c
		summarizeBy: sum
		sourceColumn: Unit_sold_by_Region

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Sales_Dataset = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Inobat\Desktop\Maab\Power BI\lesson-2_power_query\homework\Sales_Dataset.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers",{{"Product", "Product_Name"}, {"Sales_Rep", "Sales_Person"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}, {"Sale_ID", Int64.Type}, {"Region", type text}, {"Product_Name", type text}, {"Category", type text}, {"Sales_Person", type text}, {"Units_Sold", Int64.Type}, {"Unit_Price", Currency.Type}, {"Discount", Int64.Type}, {"Profit_Per_Unit", Currency.Type}, {"Total_Sale", Currency.Type}, {"Total_Profit", Currency.Type}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Filtered Rows" = Table.SelectRows(#"Inserted Year", each ([Year] = 2022)),
				    #"Reordered Columns" = Table.ReorderColumns(#"Filtered Rows",{"Sale_ID", "Date", "Region", "Total_Sale", "Product_Name", "Category", "Sales_Person", "Units_Sold", "Unit_Price", "Discount", "Profit_Per_Unit", "Total_Profit", "Year"}),
				    #"Sorted Rows" = Table.Sort(#"Reordered Columns",{{"Region", Order.Ascending}, {"Total_Sale", Order.Descending}}),
				    #"Removed Duplicates" = Table.Distinct(#"Sorted Rows", {"Sale_ID"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Duplicates","Doe","D. Doe",Replacer.ReplaceText,{"Sales_Person"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Taylor","M. Taylor",Replacer.ReplaceText,{"Sales_Person"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Replaced Value1", "Sales_category", each if [Total_Sale] <= 500 then "Low" else if [Total_Sale] >= 15000 then "High" else "Medium"),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Added Conditional Column",{"Sale_ID", "Date", "Region", "Product_Name", "Category", "Sales_Person", "Units_Sold", "Unit_Price", "Discount", "Profit_Per_Unit", "Total_Profit", "Year", "Total_Sale", "Sales_category"}),
				    #"Inserted Day" = Table.AddColumn(#"Reordered Columns1", "Day", each Date.Day([Date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Day", "Month Name", each Date.MonthName([Date]), type text),
				    #"Added Custom" = Table.AddColumn(#"Inserted Month Name", "Region_Product", each [Region] & " " & [Product_Name]),
				    #"Grouped Rows" = Table.Group(#"Added Custom", {"Region"}, {{"Unit_sold_by_Region", each List.Sum([Units_Sold]), type nullable number}})
				in
				    #"Grouped Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

