table Sales
	lineageTag: 48f4fe41-ef7d-46b7-8a2b-8a6a93d93eac

	column Sale_ID
		dataType: int64
		formatString: 0
		lineageTag: de277fad-afc8-4db1-b675-57b5a932d7fb
		summarizeBy: count
		sourceColumn: Sale_ID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 325f7edf-1db4-4005-a37a-e74b9fd2fc17
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: ec2425f2-8b23-4ca4-a96e-9e6360b636cb
			defaultHierarchy: LocalDateTable_8630f88b-3fe7-4ba0-ac00-5f4bb4776487.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Product
		dataType: string
		lineageTag: 7d16021b-ad72-4cb9-ad2f-dbb469cc0659
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Sales_Rep
		dataType: string
		lineageTag: 43432b76-e774-4ee5-a93c-520a117f1ff1
		summarizeBy: none
		sourceColumn: Sales_Rep

		annotation SummarizationSetBy = Automatic

	column Units_Sold
		dataType: int64
		formatString: 0
		lineageTag: fecb2207-50ed-4604-9815-fadc05a59443
		summarizeBy: sum
		sourceColumn: Units_Sold

		annotation SummarizationSetBy = Automatic

	column Unit_Price
		dataType: double
		lineageTag: 448ce903-e092-4fff-bd93-093853e1241f
		summarizeBy: sum
		sourceColumn: Unit_Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discount
		dataType: int64
		formatString: 0
		lineageTag: 729fcdaf-5f99-42b8-a123-b9a5abad7241
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Profit_Per_Unit
		dataType: double
		lineageTag: b2e876be-903c-4889-9438-a02c66c2c6fe
		summarizeBy: sum
		sourceColumn: Profit_Per_Unit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_Sale
		dataType: double
		lineageTag: 36a13e41-f1d0-4381-b7f1-88650d0cd549
		summarizeBy: sum
		sourceColumn: Total_Sale

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Attribute
		dataType: string
		lineageTag: 2ee6fd87-0881-4c1f-9568-50452d259bf2
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: string
		lineageTag: 1f2d778a-eef9-48fd-bad6-c723f286648a
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column West
		dataType: double
		lineageTag: a43fe1ca-4f85-4982-9306-146148e430cb
		summarizeBy: sum
		sourceColumn: West

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column South
		dataType: double
		lineageTag: 01aa66d5-7dfd-47df-8cd1-12f3438dcf76
		summarizeBy: sum
		sourceColumn: South

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column East
		dataType: double
		lineageTag: 5136d944-26a3-4adb-b771-15c51efb1177
		summarizeBy: sum
		sourceColumn: East

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column North
		dataType: double
		lineageTag: 285bbf76-155d-4a4b-94d6-39e07e5fc8d1
		summarizeBy: sum
		sourceColumn: North

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Sales = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Inobat\Desktop\Maab\Power BI\lesson-2_power_query\homework\Sales_Dataset.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Sale_ID", Int64.Type}, {"Date", type date}, {"Region", type text}, {"Product", type text}, {"Category", type text}, {"Sales_Rep", type text}, {"Units_Sold", Int64.Type}, {"Unit_Price", type number}, {"Discount", Int64.Type}, {"Profit_Per_Unit", type number}, {"Total_Sale", type number}, {"Total_Profit", type number}}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Changed Type", {"Sale_ID", "Date", "Region", "Product", "Sales_Rep", "Units_Sold", "Unit_Price", "Discount", "Profit_Per_Unit", "Total_Sale", "Total_Profit"}, "Attribute", "Value"),
				    #"Pivoted Column" = Table.Pivot(#"Unpivoted Columns", List.Distinct(#"Unpivoted Columns"[Region]), "Region", "Total_Profit", List.Sum)
				in
				    #"Pivoted Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

