table FactTransaction
	lineageTag: 785e75b9-7689-4f6f-8273-f62b49b981d3

	column TransactionDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0d1c55b5-8bc1-49c4-b041-8335e50d498d
		summarizeBy: none
		sourceColumn: TransactionDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TransactionAmount
		dataType: int64
		formatString: 0
		lineageTag: 5802956c-0523-4a3c-88f2-f8d12096ebec
		summarizeBy: sum
		sourceColumn: TransactionAmount

		annotation SummarizationSetBy = Automatic

	column 'Running total' = CALCULATE(SUM(FactTransaction[TransactionAmount]),FILTER(FactTransaction,EARLIER(FactTransaction[TransactionDate]) >= FactTransaction[TransactionDate]))
		formatString: 0
		lineageTag: d73d5b68-f442-48c7-8655-f9c5b5f409ba
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Prev_day_value = CALCULATE(SUM(FactTransaction[TransactionAmount]),FILTER(FactTransaction,DATEDIFF(FactTransaction[TransactionDate],EARLIER(FactTransaction[TransactionDate]),DAY)=1))
		formatString: 0
		lineageTag: 2fbebebf-b353-47f3-b5c8-a10a8a4b88da
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column PrevTransactionAmount = ```
			
			VAR PrevDate = 
			    CALCULATE(
			        MAX(FactTransaction[TransactionDate]),
			        FILTER(
			            FactTransaction,
			            FactTransaction[TransactionDate] < EARLIER(FactTransaction[TransactionDate])
			        )
			    )
			RETURN
			    CALCULATE(
			        MAX(FactTransaction[TransactionAmount]),
			        FILTER(
			            FactTransaction,
			            FactTransaction[TransactionDate] = PrevDate
			        )
			    )
			```
		formatString: 0
		lineageTag: 39441ff1-0bcd-44ff-90f4-a0c6648e6d9d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition FactTransaction = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Inobat\Desktop\Maab\Power BI\lesson-11\source_for_Earlier.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"TransactionDate", type date}, {"TransactionAmount", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

