table 'Measures Table'
	lineageTag: 0fa43212-ffda-4597-a952-2250e7078f52

	measure 'Running total'
		lineageTag: d34b1368-3d21-4967-99df-3dbac6081d0f

	measure Top_Genre = TOPN(1,VALUES(Movies[Genre]),CALCULATE(SUM(Movies[Budget])),DESC)
		lineageTag: 24483819-6e64-4d3c-a709-723b725c49e0

	column Column1
		dataType: string
		lineageTag: 19062569-d2d0-49e0-99d4-e9d6a93c7aaa
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition 'Measures Table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

