table DimCustomer
	lineageTag: 59dd8c98-5a5c-4581-b520-574240935a7d

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 0c0690e5-d063-4c5d-914b-e12d90f2c1f3
		summarizeBy: count
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column GeographyKey
		dataType: int64
		formatString: 0
		lineageTag: 35c4bd77-1116-4def-94c1-3f30446cda9d
		summarizeBy: count
		sourceColumn: GeographyKey

		annotation SummarizationSetBy = Automatic

	column CustomerAlternateKey
		dataType: string
		lineageTag: 0c7d2bf4-2be5-403e-956a-8399d3350473
		summarizeBy: none
		sourceColumn: CustomerAlternateKey

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: 9f0700c0-70a2-474f-b243-1974f69fbd36
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: c85398b9-ea61-4f0e-b5a4-ebc298dac9c5
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column MiddleName
		dataType: string
		lineageTag: 75a20814-eda2-468c-ab18-6a2dc26c0e68
		summarizeBy: none
		sourceColumn: MiddleName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 91745769-ab3e-4da9-81b9-fabb62988298
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column NameStyle
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 90e7fe4a-b4a9-4244-a24d-3e45fc1ee1f2
		summarizeBy: none
		sourceColumn: NameStyle

		annotation SummarizationSetBy = Automatic

	column BirthDate
		dataType: dateTime
		formatString: General Date
		lineageTag: a145f1c8-0d5b-477c-8ab4-972fd34f1e44
		summarizeBy: none
		sourceColumn: BirthDate

		variation Variation
			isDefault
			relationship: 54e01c72-bca4-4072-8a1f-156f01443fd2
			defaultHierarchy: LocalDateTable_050f1270-5d0b-4ada-9323-3a08d61a9fde.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column MaritalStatus
		dataType: string
		lineageTag: 7ed8b048-4f51-4abd-a100-cf827d6e4be5
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column Suffix
		dataType: string
		lineageTag: 826c00de-52eb-46a3-877c-0fd00c7c81a1
		summarizeBy: none
		sourceColumn: Suffix

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: d2e2c093-7142-44f9-adc6-d6b218548c5b
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column EmailAddress
		dataType: string
		lineageTag: 3f100e80-08ec-4730-8794-a97502ef2dfa
		summarizeBy: none
		sourceColumn: EmailAddress

		annotation SummarizationSetBy = Automatic

	column YearlyIncome
		dataType: double
		lineageTag: 99ff318c-806b-4a1c-8d84-bd2fd84d2b21
		summarizeBy: sum
		sourceColumn: YearlyIncome

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalChildren
		dataType: int64
		formatString: 0
		lineageTag: 74f4064c-2752-47bd-8404-4cfa7fb91e6e
		summarizeBy: sum
		sourceColumn: TotalChildren

		annotation SummarizationSetBy = Automatic

	column NumberChildrenAtHome
		dataType: int64
		formatString: 0
		lineageTag: 49e787e7-39b0-4142-a88e-6087d51882d9
		summarizeBy: sum
		sourceColumn: NumberChildrenAtHome

		annotation SummarizationSetBy = Automatic

	column EnglishEducation
		dataType: string
		lineageTag: 1a677621-efcd-400d-8910-08803d89180a
		summarizeBy: none
		sourceColumn: EnglishEducation

		annotation SummarizationSetBy = Automatic

	column SpanishEducation
		dataType: string
		lineageTag: 872aae59-c226-428e-b937-3af86a195d74
		summarizeBy: none
		sourceColumn: SpanishEducation

		annotation SummarizationSetBy = Automatic

	column FrenchEducation
		dataType: string
		lineageTag: def33ce3-d6aa-4e84-b925-2d7bc742c484
		summarizeBy: none
		sourceColumn: FrenchEducation

		annotation SummarizationSetBy = Automatic

	column EnglishOccupation
		dataType: string
		lineageTag: 6a73d1b6-fd20-4840-af70-4bcd5717d7fe
		summarizeBy: none
		sourceColumn: EnglishOccupation

		annotation SummarizationSetBy = Automatic

	column SpanishOccupation
		dataType: string
		lineageTag: 4aabe649-5e14-40f0-a899-260e5e0fcfa0
		summarizeBy: none
		sourceColumn: SpanishOccupation

		annotation SummarizationSetBy = Automatic

	column FrenchOccupation
		dataType: string
		lineageTag: fa99573d-db06-48f8-90dd-fbd86fc30675
		summarizeBy: none
		sourceColumn: FrenchOccupation

		annotation SummarizationSetBy = Automatic

	column HouseOwnerFlag
		dataType: string
		lineageTag: 3e4acd60-6a4a-43ff-a129-46055f06dd5d
		summarizeBy: none
		sourceColumn: HouseOwnerFlag

		annotation SummarizationSetBy = Automatic

	column NumberCarsOwned
		dataType: int64
		formatString: 0
		lineageTag: 0dce0dfe-3344-40e7-a836-e7af29328556
		summarizeBy: sum
		sourceColumn: NumberCarsOwned

		annotation SummarizationSetBy = Automatic

	column AddressLine1
		dataType: string
		lineageTag: fc2b4c3d-0454-44e5-98f6-5b3d38b29d50
		summarizeBy: none
		sourceColumn: AddressLine1

		annotation SummarizationSetBy = Automatic

	column AddressLine2
		dataType: string
		lineageTag: cdf0bcc0-bd77-4ad6-9e83-7e0d6f3a9d92
		summarizeBy: none
		sourceColumn: AddressLine2

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: 3cc9bd3f-621e-438e-bce5-3da6a850aac1
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column DateFirstPurchase
		dataType: dateTime
		formatString: General Date
		lineageTag: 6639b4d9-8e7e-4338-aa71-b5aadbe45e3a
		summarizeBy: none
		sourceColumn: DateFirstPurchase

		variation Variation
			isDefault
			relationship: cb77f920-2de6-49cf-8b6c-3c6f8fa26017
			defaultHierarchy: LocalDateTable_bf01d945-3a21-4a77-8fda-5a41bb5f5623.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column CommuteDistance
		dataType: string
		lineageTag: 513d353d-d0fd-46a0-86c9-6ce8392e59ad
		summarizeBy: none
		sourceColumn: CommuteDistance

		annotation SummarizationSetBy = Automatic

	column 'Full name'
		dataType: string
		lineageTag: 05a0e3c6-0ae2-4d60-a76f-bc8c2574a632
		summarizeBy: none
		sourceColumn: Full name

		annotation SummarizationSetBy = Automatic

	column 'full name1'
		dataType: string
		lineageTag: 0eb513da-bed2-42e7-b65c-fcc355f05c71
		summarizeBy: none
		sourceColumn: full name1

		annotation SummarizationSetBy = Automatic

	partition DimCustomer = m
		mode: import
		source =
				let
				    english_edu = EnglishEducation,
				    Source = Sql.Database("DESKTOP-CSSCKLQ", "AdventureWorksDW2019", [Query="#(lf)select * from [dbo].[DimCustomer]#(lf)where EnglishEducation = '"&english_edu&"'#(lf)"]),
				    #"Added Custom" = Table.AddColumn(Source, "Full name", each [FirstName] & " " & [MiddleName] & " " & [LastName]),
				    #"Inserted Merged Column" = Table.AddColumn(#"Added Custom", "full name1", each Text.Combine({[FirstName], [MiddleName], [LastName]}, " "), type text)
				in
				    #"Inserted Merged Column"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

