table English_edu
	lineageTag: df0c1d20-9cef-490e-80a5-85d989c26c85

	column English_edu
		dataType: string
		lineageTag: 381b868d-a334-4a2f-b9ba-0c00acf61c73
		summarizeBy: none
		sourceColumn: English_edu

		annotation SummarizationSetBy = Automatic

	column 'test_fields.CustomerKey'
		dataType: string
		lineageTag: 18661c8c-0730-4e81-ac41-55323c96b234
		summarizeBy: none
		sourceColumn: test_fields.CustomerKey

		annotation SummarizationSetBy = Automatic

	column 'test_fields.GeographyKey'
		dataType: string
		lineageTag: f4063552-69dc-4465-9b5b-7a1fb2bf1426
		summarizeBy: none
		sourceColumn: test_fields.GeographyKey

		annotation SummarizationSetBy = Automatic

	column 'test_fields.CustomerAlternateKey'
		dataType: string
		lineageTag: f86db264-0459-4199-9656-abab613ab840
		summarizeBy: none
		sourceColumn: test_fields.CustomerAlternateKey

		annotation SummarizationSetBy = Automatic

	column 'test_fields.Title'
		dataType: string
		lineageTag: 6826975e-b5f6-4d76-914f-012aaf8d0d54
		summarizeBy: none
		sourceColumn: test_fields.Title

		annotation SummarizationSetBy = Automatic

	column 'test_fields.FirstName'
		dataType: string
		lineageTag: db51ae80-c8ee-436f-8482-e5c31ecb7257
		summarizeBy: none
		sourceColumn: test_fields.FirstName

		annotation SummarizationSetBy = Automatic

	column 'test_fields.MiddleName'
		dataType: string
		lineageTag: 192f7cb5-602f-4c91-898a-f2ca34291353
		summarizeBy: none
		sourceColumn: test_fields.MiddleName

		annotation SummarizationSetBy = Automatic

	column 'test_fields.LastName'
		dataType: string
		lineageTag: bb6bda28-3f43-4b34-8b19-23f6a106c665
		summarizeBy: none
		sourceColumn: test_fields.LastName

		annotation SummarizationSetBy = Automatic

	column 'test_fields.NameStyle'
		dataType: string
		lineageTag: 0d500826-b803-43f6-b316-9162dc7f2f6e
		summarizeBy: none
		sourceColumn: test_fields.NameStyle

		annotation SummarizationSetBy = Automatic

	column 'test_fields.BirthDate'
		dataType: string
		lineageTag: c31561a2-299b-4f3a-8537-5407608b1449
		summarizeBy: none
		sourceColumn: test_fields.BirthDate

		annotation SummarizationSetBy = Automatic

	column 'test_fields.MaritalStatus'
		dataType: string
		lineageTag: 68ce389c-cbcb-4214-b40c-883f9e890a05
		summarizeBy: none
		sourceColumn: test_fields.MaritalStatus

		annotation SummarizationSetBy = Automatic

	column 'test_fields.Suffix'
		dataType: string
		lineageTag: a01c9090-8c76-4cc5-8a7e-6fca21448209
		summarizeBy: none
		sourceColumn: test_fields.Suffix

		annotation SummarizationSetBy = Automatic

	column 'test_fields.Gender'
		dataType: string
		lineageTag: 8d300cdc-4caa-469b-a908-bf240cbf44f6
		summarizeBy: none
		sourceColumn: test_fields.Gender

		annotation SummarizationSetBy = Automatic

	column 'test_fields.EmailAddress'
		dataType: string
		lineageTag: c7eb39f3-1053-4e5c-aa8c-fe0198b1d3e4
		summarizeBy: none
		sourceColumn: test_fields.EmailAddress

		annotation SummarizationSetBy = Automatic

	column 'test_fields.YearlyIncome'
		dataType: string
		lineageTag: 359788a5-e282-4375-a07c-5923c3d47326
		summarizeBy: none
		sourceColumn: test_fields.YearlyIncome

		annotation SummarizationSetBy = Automatic

	column 'test_fields.TotalChildren'
		dataType: string
		lineageTag: a24a1ec4-7112-42cb-9e84-e6f4801996a6
		summarizeBy: none
		sourceColumn: test_fields.TotalChildren

		annotation SummarizationSetBy = Automatic

	column 'test_fields.NumberChildrenAtHome'
		dataType: string
		lineageTag: ee724a61-08d9-441e-940f-56d766bb14ab
		summarizeBy: none
		sourceColumn: test_fields.NumberChildrenAtHome

		annotation SummarizationSetBy = Automatic

	column 'test_fields.EnglishEducation'
		dataType: string
		lineageTag: 54069367-105f-4fa6-ac4a-895de91c53ae
		summarizeBy: none
		sourceColumn: test_fields.EnglishEducation

		annotation SummarizationSetBy = Automatic

	column 'test_fields.SpanishEducation'
		dataType: string
		lineageTag: 0709365f-8c3b-4ec9-89b6-f508e8fd3c61
		summarizeBy: none
		sourceColumn: test_fields.SpanishEducation

		annotation SummarizationSetBy = Automatic

	column 'test_fields.FrenchEducation'
		dataType: string
		lineageTag: 222fb4af-3597-4c4c-8cfb-1581bf5c715a
		summarizeBy: none
		sourceColumn: test_fields.FrenchEducation

		annotation SummarizationSetBy = Automatic

	column 'test_fields.EnglishOccupation'
		dataType: string
		lineageTag: d74940c8-966c-4d2c-aa1e-3015757feaa8
		summarizeBy: none
		sourceColumn: test_fields.EnglishOccupation

		annotation SummarizationSetBy = Automatic

	column 'test_fields.SpanishOccupation'
		dataType: string
		lineageTag: 4b7e0779-4d4b-4a24-bce6-c422c298b0f5
		summarizeBy: none
		sourceColumn: test_fields.SpanishOccupation

		annotation SummarizationSetBy = Automatic

	column 'test_fields.FrenchOccupation'
		dataType: string
		lineageTag: c8eae2ce-cca3-48af-a792-379f9cebde4d
		summarizeBy: none
		sourceColumn: test_fields.FrenchOccupation

		annotation SummarizationSetBy = Automatic

	column 'test_fields.HouseOwnerFlag'
		dataType: string
		lineageTag: ccd8f8be-b32a-463e-8667-e3b5c162e865
		summarizeBy: none
		sourceColumn: test_fields.HouseOwnerFlag

		annotation SummarizationSetBy = Automatic

	column 'test_fields.NumberCarsOwned'
		dataType: string
		lineageTag: 24d61759-ed65-44bb-8bb8-54f3784d5f88
		summarizeBy: none
		sourceColumn: test_fields.NumberCarsOwned

		annotation SummarizationSetBy = Automatic

	column 'test_fields.AddressLine1'
		dataType: string
		lineageTag: 98d53523-1c33-4775-84b7-8c6faec5205f
		summarizeBy: none
		sourceColumn: test_fields.AddressLine1

		annotation SummarizationSetBy = Automatic

	column 'test_fields.AddressLine2'
		dataType: string
		lineageTag: 5e1a9321-bc85-4fb1-96c6-89c1b390005f
		summarizeBy: none
		sourceColumn: test_fields.AddressLine2

		annotation SummarizationSetBy = Automatic

	column 'test_fields.Phone'
		dataType: string
		lineageTag: c48dc179-9a1d-4c2f-bc62-4e9032b5abf0
		summarizeBy: none
		sourceColumn: test_fields.Phone

		annotation SummarizationSetBy = Automatic

	column 'test_fields.DateFirstPurchase'
		dataType: string
		lineageTag: a5ac7439-6e3d-4232-af44-18e1b52549ec
		summarizeBy: none
		sourceColumn: test_fields.DateFirstPurchase

		annotation SummarizationSetBy = Automatic

	column 'test_fields.CommuteDistance'
		dataType: string
		lineageTag: 3cc45da9-b5ec-4da5-bcd7-95f3ce2a2b1f
		summarizeBy: none
		sourceColumn: test_fields.CommuteDistance

		annotation SummarizationSetBy = Automatic

	partition English_edu = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Inobat\Desktop\Maab\Power BI\lesson-4_SQL\multiple_fields.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"English_edu", type text}}),
				    #"Invoked Custom Function" = Table.AddColumn(#"Changed Type", "test_fields", each GetAllCustomersByEnglishEdu([English_edu])),
				    #"Expanded test_fields" = Table.ExpandTableColumn(#"Invoked Custom Function", "test_fields", {"CustomerKey", "GeographyKey", "CustomerAlternateKey", "Title", "FirstName", "MiddleName", "LastName", "NameStyle", "BirthDate", "MaritalStatus", "Suffix", "Gender", "EmailAddress", "YearlyIncome", "TotalChildren", "NumberChildrenAtHome", "EnglishEducation", "SpanishEducation", "FrenchEducation", "EnglishOccupation", "SpanishOccupation", "FrenchOccupation", "HouseOwnerFlag", "NumberCarsOwned", "AddressLine1", "AddressLine2", "Phone", "DateFirstPurchase", "CommuteDistance"}, {"test_fields.CustomerKey", "test_fields.GeographyKey", "test_fields.CustomerAlternateKey", "test_fields.Title", "test_fields.FirstName", "test_fields.MiddleName", "test_fields.LastName", "test_fields.NameStyle", "test_fields.BirthDate", "test_fields.MaritalStatus", "test_fields.Suffix", "test_fields.Gender", "test_fields.EmailAddress", "test_fields.YearlyIncome", "test_fields.TotalChildren", "test_fields.NumberChildrenAtHome", "test_fields.EnglishEducation", "test_fields.SpanishEducation", "test_fields.FrenchEducation", "test_fields.EnglishOccupation", "test_fields.SpanishOccupation", "test_fields.FrenchOccupation", "test_fields.HouseOwnerFlag", "test_fields.NumberCarsOwned", "test_fields.AddressLine1", "test_fields.AddressLine2", "test_fields.Phone", "test_fields.DateFirstPurchase", "test_fields.CommuteDistance"})
				in
				    #"Expanded test_fields"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

