table 'Measures Table'
	lineageTag: 44f5ce9f-226a-4263-a823-19122c1f90e6

	measure 'Total amount' = SUM(personal_budget_data[TransactionAmount])
		displayFolder: Total
		lineageTag: 9c9b080c-9f02-4df5-aaf2-01aa97b2297c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total amount (DateSMTD)' = CALCULATE([Total amount], DATESMTD('Date'[Date]))
		displayFolder: MTD/QTD/YTD
		lineageTag: a884f8d5-370f-4089-b656-4c0df38909bf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total amount (DateSQTD)' = CALCULATE([Total amount], DATESQTD('Date'[Date]))
		displayFolder: MTD/QTD/YTD
		lineageTag: 44470c19-72b5-44a2-9329-1854d48258c4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total amount (DateSYTD)' = CALCULATE([Total amount], DATESYTD('Date'[Date]))
		displayFolder: MTD/QTD/YTD
		lineageTag: ce94a835-6e00-41eb-9331-9e4a8fa600b7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total amount (TotalQTD)' = TOTALQTD([Total amount],'Date'[Date])
		displayFolder: Total/MTD/YTD/QTD
		lineageTag: d43fcfb2-5cde-465d-a929-ac94e78bf5ee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total amount (TotalMTD)' = TOTALMTD([Total amount],'Date'[Date])
		displayFolder: Total/MTD/YTD/QTD
		lineageTag: 25e53790-96ab-43fe-9dd5-de7e0474ff1c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total amount (TotalYTD)' = TOTALYTD([Total amount],'Date'[Date])
		displayFolder: Total/MTD/YTD/QTD
		lineageTag: a6d704e2-e26e-4f57-8148-104e10ec0542

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MoM %' =
			
			VAR current_month_sales = [Total amount]
			VAR prev_month_sales = CALCULATE([Total amount],DATEADD('Date'[Date],-1,MONTH))
			RETURN IF(NOT(ISBLANK(current_month_sales)) && NOT(ISBLANK(prev_month_sales)), DIVIDE(current_month_sales-prev_month_sales, prev_month_sales, BLANK()))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MoM/QoQ/YoY
		lineageTag: 9689b1c2-a3dc-42d8-abe0-287b8c7b4ee3

	measure prev_month_sales = CALCULATE([Total amount],DATEADD('Date'[Date],-1,MONTH))
		displayFolder: Total
		lineageTag: 29d06671-32be-4991-8bb2-9da72f07b8cf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QoQ %' =
			
			VAR current_quarter_sales = [Total amount]
			VAR prev_quarter_sales = CALCULATE([Total amount],DATEADD('Date'[Date],-1,QUARTER))
			RETURN IF(NOT(ISBLANK(current_quarter_sales)) && NOT(ISBLANK(prev_quarter_sales)), DIVIDE(current_quarter_sales-prev_quarter_sales, prev_quarter_sales, BLANK()))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MoM/QoQ/YoY
		lineageTag: 2f38a932-d013-4792-ae6b-e1bdaeb593f7

	measure 'YoY %' =
			
			VAR current_year_sales = [Total amount]
			VAR prev_year_sales = CALCULATE([Total amount],DATEADD('Date'[Date],-1,YEAR))
			RETURN IF(NOT(ISBLANK(current_year_sales)) && NOT(ISBLANK(prev_year_sales)), DIVIDE(current_year_sales-prev_year_sales, prev_year_sales, BLANK()))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MoM/QoQ/YoY
		lineageTag: e26e4705-ddbf-4992-a4f7-f76885e99477

	measure 'Total amount (Prev month)' = CALCULATE([Total amount], PREVIOUSMONTH('Date'[Date]))
		lineageTag: 1a002d71-895c-4208-90aa-8910ba56da50

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MTDoPM %' =
			
			var current_mtd = [Total amount (DateSMTD)]
			var prev_month = [Total amount (Prev month)]
			RETURN IF(NOT(ISBLANK(current_mtd)) && NOT(ISBLANK(prev_month)), DIVIDE(current_mtd-prev_month,prev_month), BLANK())
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a0a2661f-ed0d-408d-aa9b-add5bc800eab

	partition 'Measures Table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

