table Multiple_deps
	lineageTag: 30b8b8c6-971e-42d4-9bc7-5a4b45da18cb

	column Departments
		dataType: string
		lineageTag: f82fe3f4-6ffd-4032-884a-e6ef2762f1ac
		summarizeBy: none
		sourceColumn: Departments

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.EmployeeKey'
		dataType: string
		lineageTag: 170e5427-2360-4ee4-8742-9bd12f6b64ff
		summarizeBy: none
		sourceColumn: otherdetails.EmployeeKey

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.ParentEmployeeKey'
		dataType: string
		lineageTag: fdda8924-efe5-41da-b608-24585fa0a13d
		summarizeBy: none
		sourceColumn: otherdetails.ParentEmployeeKey

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.EmployeeNationalIDAlternateKey'
		dataType: string
		lineageTag: c1bdc224-1ee6-4767-84ca-d71c62b636cd
		summarizeBy: none
		sourceColumn: otherdetails.EmployeeNationalIDAlternateKey

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.ParentEmployeeNationalIDAlternateKey'
		dataType: string
		lineageTag: 7fd65a0a-ac60-4616-88fc-b68dda1751b0
		summarizeBy: none
		sourceColumn: otherdetails.ParentEmployeeNationalIDAlternateKey

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.SalesTerritoryKey'
		dataType: string
		lineageTag: d8d90ee8-ab1f-4514-98f5-ec5fd6cf3c46
		summarizeBy: none
		sourceColumn: otherdetails.SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.FirstName'
		dataType: string
		lineageTag: 74c932bc-3244-41c1-a5a6-f02386c6dfb9
		summarizeBy: none
		sourceColumn: otherdetails.FirstName

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.LastName'
		dataType: string
		lineageTag: 0fcb5152-dc6f-4d5c-a88e-f6e19376f7a4
		summarizeBy: none
		sourceColumn: otherdetails.LastName

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.MiddleName'
		dataType: string
		lineageTag: 429b3cc6-e9dd-4610-bfb9-1e624d3e32b5
		summarizeBy: none
		sourceColumn: otherdetails.MiddleName

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.NameStyle'
		dataType: string
		lineageTag: 75793045-357c-4b45-aef7-80d8eb55b338
		summarizeBy: none
		sourceColumn: otherdetails.NameStyle

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.Title'
		dataType: string
		lineageTag: a1cf8da9-80a6-402b-88d6-7d1d2bfdadcc
		summarizeBy: none
		sourceColumn: otherdetails.Title

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.HireDate'
		dataType: string
		lineageTag: 483b303c-9214-48cf-ac88-6236702c0b96
		summarizeBy: none
		sourceColumn: otherdetails.HireDate

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.BirthDate'
		dataType: string
		lineageTag: a16113b5-ec19-4f70-a48d-da56d35ee126
		summarizeBy: none
		sourceColumn: otherdetails.BirthDate

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.LoginID'
		dataType: string
		lineageTag: 43d4db2e-c7ec-4d57-b8db-fd703c5a3c58
		summarizeBy: none
		sourceColumn: otherdetails.LoginID

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.EmailAddress'
		dataType: string
		lineageTag: 102c7b4a-e3e5-4b51-a0b5-0dc6d4bb7488
		summarizeBy: none
		sourceColumn: otherdetails.EmailAddress

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.Phone'
		dataType: string
		lineageTag: feb646cd-e44b-489e-9e43-a2911f301330
		summarizeBy: none
		sourceColumn: otherdetails.Phone

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.MaritalStatus'
		dataType: string
		lineageTag: 683d3096-8ee7-44d4-8ca7-8fb18be31ce5
		summarizeBy: none
		sourceColumn: otherdetails.MaritalStatus

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.EmergencyContactName'
		dataType: string
		lineageTag: bfe706d0-8510-4956-a166-93914be05ce5
		summarizeBy: none
		sourceColumn: otherdetails.EmergencyContactName

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.EmergencyContactPhone'
		dataType: string
		lineageTag: 7e76112e-da2a-47bf-ba25-812bbbd9db45
		summarizeBy: none
		sourceColumn: otherdetails.EmergencyContactPhone

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.SalariedFlag'
		dataType: string
		lineageTag: da47342c-26db-49b5-8a11-43ba011234fc
		summarizeBy: none
		sourceColumn: otherdetails.SalariedFlag

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.Gender'
		dataType: string
		lineageTag: 57bfe621-fb96-4da6-b124-5eb3af165c28
		summarizeBy: none
		sourceColumn: otherdetails.Gender

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.PayFrequency'
		dataType: string
		lineageTag: 8b428459-667e-4b72-a1df-bc6dd4056e6a
		summarizeBy: none
		sourceColumn: otherdetails.PayFrequency

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.BaseRate'
		dataType: string
		lineageTag: 63d58ab8-c8dd-4f99-a9bc-6f60e326bbc8
		summarizeBy: none
		sourceColumn: otherdetails.BaseRate

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.VacationHours'
		dataType: string
		lineageTag: b9c78a52-9212-48ac-b346-204e3aece213
		summarizeBy: none
		sourceColumn: otherdetails.VacationHours

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.SickLeaveHours'
		dataType: string
		lineageTag: e968a6c0-84ac-4722-9532-77ec15933a8d
		summarizeBy: none
		sourceColumn: otherdetails.SickLeaveHours

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.CurrentFlag'
		dataType: string
		lineageTag: 89fa15e2-fcfa-4395-8667-a818bd83b19c
		summarizeBy: none
		sourceColumn: otherdetails.CurrentFlag

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.SalesPersonFlag'
		dataType: string
		lineageTag: 8bb2c009-0277-45b4-bb97-f13c5d607df9
		summarizeBy: none
		sourceColumn: otherdetails.SalesPersonFlag

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.DepartmentName'
		dataType: string
		lineageTag: beb3cc1e-cc83-472b-bd91-e0a7fd376588
		summarizeBy: none
		sourceColumn: otherdetails.DepartmentName

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.StartDate'
		dataType: string
		lineageTag: a036ce2e-2b6c-4a6c-bc7a-9d64ec310e2a
		summarizeBy: none
		sourceColumn: otherdetails.StartDate

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.EndDate'
		dataType: string
		lineageTag: b1106b60-a4e0-4ba8-8ccf-2f84fdb06e6b
		summarizeBy: none
		sourceColumn: otherdetails.EndDate

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.Status'
		dataType: string
		lineageTag: 576cc611-984a-44b1-a2aa-3708ea019066
		summarizeBy: none
		sourceColumn: otherdetails.Status

		annotation SummarizationSetBy = Automatic

	column 'otherdetails.EmployeePhoto'
		dataType: string
		lineageTag: c300f27c-9887-4f2a-827c-e1c5486d786e
		summarizeBy: none
		sourceColumn: otherdetails.EmployeePhoto

		annotation SummarizationSetBy = Automatic

	partition Multiple_deps = m
		mode: import
		queryGroup: 'GetAllEmployeesByDepName func'
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Inobat\Desktop\Maab\Power BI\lesson-4_SQL\homework_3\departments.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Invoked Custom Function" = Table.AddColumn(#"Promoted Headers", "otherdetails", each GetAllEmployeesByDepName([Departments])),
				    #"Expanded otherdetails" = Table.ExpandTableColumn(#"Invoked Custom Function", "otherdetails", {"EmployeeKey", "ParentEmployeeKey", "EmployeeNationalIDAlternateKey", "ParentEmployeeNationalIDAlternateKey", "SalesTerritoryKey", "FirstName", "LastName", "MiddleName", "NameStyle", "Title", "HireDate", "BirthDate", "LoginID", "EmailAddress", "Phone", "MaritalStatus", "EmergencyContactName", "EmergencyContactPhone", "SalariedFlag", "Gender", "PayFrequency", "BaseRate", "VacationHours", "SickLeaveHours", "CurrentFlag", "SalesPersonFlag", "DepartmentName", "StartDate", "EndDate", "Status", "EmployeePhoto"}, {"otherdetails.EmployeeKey", "otherdetails.ParentEmployeeKey", "otherdetails.EmployeeNationalIDAlternateKey", "otherdetails.ParentEmployeeNationalIDAlternateKey", "otherdetails.SalesTerritoryKey", "otherdetails.FirstName", "otherdetails.LastName", "otherdetails.MiddleName", "otherdetails.NameStyle", "otherdetails.Title", "otherdetails.HireDate", "otherdetails.BirthDate", "otherdetails.LoginID", "otherdetails.EmailAddress", "otherdetails.Phone", "otherdetails.MaritalStatus", "otherdetails.EmergencyContactName", "otherdetails.EmergencyContactPhone", "otherdetails.SalariedFlag", "otherdetails.Gender", "otherdetails.PayFrequency", "otherdetails.BaseRate", "otherdetails.VacationHours", "otherdetails.SickLeaveHours", "otherdetails.CurrentFlag", "otherdetails.SalesPersonFlag", "otherdetails.DepartmentName", "otherdetails.StartDate", "otherdetails.EndDate", "otherdetails.Status", "otherdetails.EmployeePhoto"})
				in
				    #"Expanded otherdetails"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

