table Songs
	lineageTag: c091d828-dccf-48cb-a56c-883c22d81e26

	column Artist
		dataType: string
		lineageTag: 6b393748-53cf-404a-adf1-b370ba5282b8
		summarizeBy: none
		sourceColumn: Artist

		annotation SummarizationSetBy = Automatic

	column Song
		dataType: string
		lineageTag: 39ef5fc5-a5ab-4126-baca-135f02816ac7
		summarizeBy: none
		sourceColumn: Song

		annotation SummarizationSetBy = Automatic

	partition Songs = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Inobat\Desktop\Maab\Power BI\lesson-3_power_bi,power_query\"&SongTypes), null, true),
				    Songs_Sheet = Source{[Item="Songs",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Songs_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Artist", type text}, {"Song", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

