table 'Measures Table'
	lineageTag: a3db0da4-458e-4e0b-b32d-c5edcaa5e136

	measure '% of region' = DIVIDE(CALCULATE(SUM(FactInternetSales[SalesAmount]),ALLEXCEPT(DimSalesTerritory,DimSalesTerritory[SalesTerritoryRegion])), CALCULATE(SUM(FactInternetSales[SalesAmount]),all(DimSalesTerritory)))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2107bcfa-7a49-4772-9a2e-afa639148589

	column Column
		formatString: 0
		lineageTag: 1dddd9af-9f6e-4690-afe4-c3eeb1511b45
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'Measures Table' = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = b95ebdd712f6449ea54c0739ace0857f

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

