table company_mast
	lineageTag: 3adf1010-b97f-44cf-b55a-81b92c26cc47

	column COM_ID
		dataType: int64
		formatString: 0
		lineageTag: 3548b953-af70-4308-9244-55c60e425b8c
		summarizeBy: none
		sourceColumn: COM_ID

		annotation SummarizationSetBy = Automatic

	column COM_NAME
		dataType: string
		lineageTag: 41158f35-f23d-43dd-9270-f8ece447b664
		summarizeBy: none
		sourceColumn: COM_NAME

		annotation SummarizationSetBy = Automatic

	partition company_mast = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Inobat\Desktop\Maab\Power BI\lesson-3_power_bi,power_query\Company.xlsx"), null, true),
				    company_mast_Sheet = Source{[Item="company_mast",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(company_mast_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"COM_ID", Int64.Type}, {"COM_NAME", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

