table item_mast
	lineageTag: 9572c3fb-bc38-441e-b50f-4f5f745501aa

	column PRO_COM
		dataType: int64
		formatString: 0
		lineageTag: c333e8ec-a64c-472a-938e-29416c6a1a76
		summarizeBy: none
		sourceColumn: PRO_COM

		annotation SummarizationSetBy = Automatic

	column Maxprice
		dataType: double
		lineageTag: 4334fdaa-35e0-467b-9d9c-3a4ba971afbc
		summarizeBy: sum
		sourceColumn: Maxprice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition item_mast = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Inobat\Desktop\Maab\Power BI\lesson-3_power_bi,power_query\Item.xlsx"), null, true),
				    item_mast_Sheet = Source{[Item="item_mast",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(item_mast_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"PRO_COM", Int64.Type}, {"PRO_ID", Int64.Type}, {"PRO_NAME", type text}, {"PRO_PRICE", Int64.Type}}),
				    #"Grouped Rows" = Table.Group(#"Changed Type", {"PRO_COM"}, {{"Maxprice", each List.Max([PRO_PRICE]), type nullable number}})
				in
				    #"Grouped Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

