table Table1
	lineageTag: d5f42586-e113-4931-a2d8-803ab547f47b

	column ID
		dataType: int64
		formatString: 0
		lineageTag: f16cf5d8-0b25-4cfc-9c9b-a01b44ce5a36
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: 32406377-9c0d-4eb3-99a8-8eda36e37461
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 7ae5a6ee-a591-420d-beeb-57499734cfca
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Salary
		dataType: int64
		formatString: 0
		lineageTag: ca32c61d-a0a1-424b-b5d2-96a1660f9156
		summarizeBy: sum
		sourceColumn: Salary

		annotation SummarizationSetBy = Automatic

	column Month1
		dataType: string
		lineageTag: 983310a7-d7cc-490b-83ed-c44c39a9b77b
		summarizeBy: none
		sourceColumn: Month1

		annotation SummarizationSetBy = Automatic

	column Month2
		dataType: string
		lineageTag: bcd017db-9f35-4363-8c7a-826084515c87
		summarizeBy: none
		sourceColumn: Month2

		annotation SummarizationSetBy = Automatic

	partition Table1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Inobat\Desktop\Maab\Power BI\lesson-3_power_bi,power_query\For Transformation.xlsx"), null, true),
				    Лист1_Sheet = Source{[Item="Лист1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Лист1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"Department", type text}, {"Name", type text}, {"Salary", Int64.Type}, {"Column5", type any}, {"Column6", type any}}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Changed Type", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Removed Top Rows" = Table.Skip(#"Removed Blank Rows",1),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Top Rows",{{"Column5", "Month1"}, {"Column6", "Month2"}}),
				    #"Removed Top Rows1" = Table.Skip(#"Renamed Columns",1),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Top Rows1","Marketin","Marketing",Replacer.ReplaceValue,{"Department"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Replaced Value",{"ID", "Department", "Name", "Salary", "Month1", "Month2"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

